import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import localFont from "next/font/local";
import "./globals.css";
import Header from '@/components/Header';
import {Montserrat} from 'next/font/google';

const inter = Montserrat({subsets: ['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedOut>
          </SignedOut>
          <SignedIn>
          </SignedIn>
          <Header/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )

}
